MVCApp/Controllers/CategoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using QuickKartDataAccessLayer;
using QuickKartDataAccessLayer.Models;

namespace MVCApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly QuickKartContext _context;
        private readonly IMapper _mapper;
        QuickKartRepository repository;
        public CategoryController(QuickKartContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
            repository = new QuickKartRepository(_context);
        }

        public IActionResult ViewCategory()
        {
            var lstCategory = repository.GetCategories();
            List<Models.Category> catObj = new List<Models.Category>();
            foreach(var category in lstCategory)
            {
                catObj.Add(_mapper.Map<Models.Category>(category));
            }
            return View(catObj);
        }
        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveCreateCategory(Models.Category id)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                try
                {
                    status = repository.AddCategory(_mapper.Map<Categories>(id));
                    if (status)
                    {
                        return RedirectToAction("ViewCategory");
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                catch (Exception)
                {
                    return View("Error");
                }
            }
            return View(id);
        }

        public IActionResult EditCategory(Models.Category id)
        {
            return View(id);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEditCategory(Models.Category id)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                try
                {
                    status = repository.UpdateCategory(_mapper.Map<Categories>(id));
                    if (status)
                    {
                        return RedirectToAction("ViewCategory");
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                catch(Exception)
                {
                    return View("Error");
                }
            }
            return View(id);
        }

        public IActionResult DeleteCategory(Models.Category id)
        {
            return View(id);
        }

        [HttpPost]
        public IActionResult SaveDeleteCategory(byte id)
        {
            bool status = false;
            var obj = _context.Categories.Find(id);
            try
            {
                status = repository.DeleteCategory(obj);
                if (status)
                {
                    return RedirectToAction("ViewCategory");
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

    }
}

MVCApp/Controllers/CustomerController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using QuickKartDataAccessLayer;
using QuickKartDataAccessLayer.Models;

namespace MVCApp.Controllers
{
    public class CustomerController : Controller
    {
        private readonly QuickKartContext _context;
        QuickKartRepository repository;
        private readonly IMapper _mapper;
        public CustomerController(QuickKartContext context, IMapper mapper)
        {
            _context = context;
            repository = new QuickKartRepository(_context);
            _mapper = mapper;
        }

        public IActionResult CustomerHome()
        {
            return View();
        }
        public ActionResult GetProduct(byte? categoryId)
        {
            ViewBag.CategoryList = repository.GetCategories();
            if (categoryId != null)
            {
                ViewData["categoryId"] = categoryId;
            }
            else
            {
                categoryId = Convert.ToByte(ViewData["categoryId"]);
            }
            ViewBag.SelectedCategory = repository.GetCategories().Where(x => x.CategoryId == categoryId).Select(x => x.CategoryName).FirstOrDefault();
            if (ViewBag.SelectedCategory == null)
                ViewBag.SelectedCategory = "--Select--";
            var productList = repository.GetProducts();
            var products = new List<Models.Product>();
            foreach (var product in productList)  
            {
                products.Add(_mapper.Map<Models.Product>(product));
            }
            var filteredProducts = products.Where(model => model.CategoryId == categoryId);
            return View(filteredProducts);
        }
        public ActionResult Feedback()
        {
            return RedirectToAction("WIP");
        }
    }
}

MVCApp/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using QuickKartDataAccessLayer;
using QuickKartDataAccessLayer.Models;

namespace MVCApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly QuickKartContext _context;
        private readonly IMapper _mapper;
        QuickKartRepository repository;


        public ProductController(QuickKartContext context, IMapper mapper)
        {
            _context = context;
            repository = new QuickKartRepository(_context);
            _mapper = mapper;
        }

        public IActionResult ViewProduct()
        {
            var lstProducts = repository.GetProducts();
            List<Models.Product> prodObj = new List<Models.Product>();
            foreach (var product in lstProducts)
            {
                prodObj.Add(_mapper.Map<Models.Product>(product));
            }
            return View(prodObj);
        }
        public IActionResult CreateProduct()  
        {
            string productId = repository.GetNextProductId();
            ViewBag.NextProductId = productId;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveCreatedProduct(Models.Product id)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                try
                {
                    status = repository.AddProduct(_mapper.Map<Products>(id));
                    if (status)
                    {
                        return RedirectToAction("ViewProduct");
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                catch (Exception)
                {
                    return View("Error");
                }
            }
            return View(id);
        }

        public IActionResult EditProduct(Models.Product prod)
        {
            return View(prod);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveEditProduct(Models.Product prod)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                try
                {
                    status = repository.UpdateProduct(_mapper.Map<Products>(prod));
                    if (status)
                    {
                        return RedirectToAction("ViewProduct");
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                catch (Exception)
                {
                    return View("Error");
                }
            }
            return View(prod);
        }

        public IActionResult DeleteProduct(Models.Product prodId)
        {
            return View(prodId);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SaveDeleteProduct(string id)
        {
            bool status = false;
            try
            {
                status = repository.DeleteProduct(id);
                if (status)
                {
                    return RedirectToAction("ViewProduct");
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception)
            {
                return View("Error");
            }
            return View(id);
        }

        public IActionResult ProductDetails(Models.Product id)
        {
            return View(id);
        }
    }
}

MVCApp/Views/Shared/Success.cshtml
@{
    ViewData["Title"] = "Success";
}

<h1>Success.</h1>
<h2>You successfully completed the action</h2>
<h3>Selected Prouduct : @TempData["ProductName"].ToString()</h3>
<h3>Quantity Purchased: @TempData["QuantityPurchased"].ToString()</h3>

MVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @Html.ActionLink("MVCAPP", "Login", "Home", new {area = ""}, new {@class ="navbar-brand"})
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="GetCoupons">Festive Offer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Terms">Terms and Conditions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="FAQ">FAQ</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-bottom footer text-muted">
        <div class="container">
            &copy; 2023 - MVCApp - <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCApp/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @Html.ActionLink("MVCAPP", "Login", "Home", new {area = ""}, new {@class ="navbar-brand"})
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="ViewProduct">View Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Product" asp-action="CreateProduct">Add Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Category" asp-action="ViewCategory">View Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Category" asp-action="CreateCategory">Add Category</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="bottom:0%;position:absolute;width:100%;text-align:center;">
        <div class="container">
            &copy; 2023 - MVCApp - <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVCApp/Views/Shared/_LayoutCustomer.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @Html.ActionLink("MVCAPP", "Login", "Home", new {area = ""}, new {@class ="navbar-brand"})
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Customer" asp-action="GetProduct">Search Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Feedback">Give Feedback</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="bottom:0%;position:absolute;width:100%;text-align:center;">
        <div class="container">
            &copy; 2023 - MVCApp - <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>